In [15]:
import csv
import re


#mypath = os.getcwd()
phonePattern = '^\d{3}-\d{3}-\d{4}$'
emailPattern = '^\w+.?\w+@\w+.[a-z]{3}$'

goodRecords = []
badPhoneRecords = []
badEmailRecords = []

#try: 
#except:
#else:


with open('ca_sample_data_a.csv') as f:
    reader = csv.DictReader(f)     #New Ordered dictionary in version 3.6 

    for row in reader:
        #better check and ignore header
        #print(row)
        #print(dict(row)) 
        if not re.search(phonePattern, row['phone1']):
            badPhoneRecords.append(row)
        elif not re.search(emailPattern, row['email']):
            badEmailRecords.append(row)
        else:
            goodRecords.append(row)

#
#print(badPhoneRecords)
#print(badEmailRecords)
            
f.close()

fieldnames = ['first_name','last_name','company_name','address','city','province',
 'postal','phone1','email','web','exam_1','exam_2','exam_3']

# try catch for open files sestions
# can be done within Pandas instead of Python too

with open('bad_phone_recs.csv', 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    
    # can use writerows command without out loop
    for row in badPhoneRecords:
        #print(row)
        writer.writerow(row)
    
csvfile.close()

with open('bad_email_recs.csv', 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    
    # can use writerows command without out loop
    for row in badEmailRecords:
        writer.writerow(row)
    
csvfile.close()

with open('good_recs.csv', 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    
    # can use writerows command without out loop
    for row in goodRecords:
        writer.writerow(row)
    
csvfile.close()

In [52]:
import pandas as pd

df = pd.read_csv('good_recs.csv')


#2 .1 Show the first 5 records using .head() 
#df.head(5)

#2.2 Show the last 10 records using .tail() 
#df.tail(10)

#2.3 Print the column names using a for loop and the .columns collection
#print (df.columns.values)
df_columns = df.columns.values
print(df_columns)
#??for i=0 to df_columns.count
#??for i in df_columns
#   print (i)
for label in df.columns
    print(label)


#2.4 Slice the DF and show records 1 to 5 (inclusive) 
#df.head(5)
#df[1:6]

#2.5 Slice the DF and show ‘last_name’ and ‘first_name’ for records 1 to 5 inclusive 
#?? df.loc[['1':'6'], ['first_name', 'last_name']]

#2.6 Show the record with index (5) (use .loc) 
#df.loc[5]
#2.7 Using .loc, show first_name and last_name for record with index 1 
# ?? df.loc[ '1', ['first_name','last_name']]

#2.8 Using .loc show first_name and last_name for records with index 1 and 5 

#2.9 Using .loc show the last_name for record with index 3 

#2.10 Try the method .describe with the dataframe and obtain stats on the exams 
df.describe()

#2.11 Using a boolean mask, show the first 5 students with an exam_1 mark of 75 or more
df[df['exam_1'] > 75].head()

['first_name' 'last_name' 'company_name' 'address' 'city' 'province'
 'postal' 'phone1' 'email' 'web' 'exam_1' 'exam_2' 'exam_3']

,first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3
2,Lourdes,Bauswell,Oklahoma Neon Inc,9547 Belmont Rd #21,Belleville,ON,K8P 1B3,613-903-7043,lourdes_bauswell@aol.com,http://www.oklahomaneoninc.com,90,95,64
3,Hannah,Edmison,M B A Paint Stores,73 Pittsford Victor Rd,Vancouver,BC,V5Z 3K2,604-334-3686,hannah@yahoo.com,http://www.mbapaintstores.com,96,95,82
4,Tom,Loeza,Sheraton Shreveport Hotel,447 Commercial St Se,LIle-Perrot,QC,J7V 4T4,514-487-6096,tom.loeza@gmail.com,http://www.sheratonshreveporthotel.com,84,79,51
7,Josefa,Opitz,Norman Gale Isuzu,136 W Grand Ave #3,Delhi,ON,N4B 1C4,519-788-7645,josefa.opitz@opitz.org,http://www.normangaleisuzu.com,83,51,57
8,Lea,Steinhaus,"James, Christopher Esq",80 Maplewood Dr #34,Bradford,ON,L3Z 2S4,905-618-8258,lsteinhaus@cox.net,http://www.jameschristopheresq.com,79,59,83